{
 "title": "Carsharing Demo Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "select now()",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "targets": [
    { "queryText": "select now()" }
   ]
  },
  {
   "title": "select count() from table(car_live_data)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select count() from table(car_live_data)"
    }
   ]
  },
  {
   "title": "select count() from car_live_data where _tp_time>earliest_ts()",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select count() from car_live_data where _tp_time>earliest_ts()"
    }
   ]
  }
 ]
}