services:
  grafana:
    user: root
    container_name: 'timeplus-proton-datasource'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.3.1}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/timeplus-proton-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/timeplus-proton-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.timeplus-proton-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: timeplus-proton-datasource

  proton:
    image: ghcr.io/timeplus-io/proton:latest
    pull_policy: always
    ports:
      - 3218:3218 # HTTP Streaming
      - 8463:8463 # TCP Streaming

  carsharing_datagen:
    image: timeplus/cardemo:latest
    pull_policy: always
    entrypoint: /bin/sh
    command: -c "sleep 15 && echo \"$$CONSOLE_CONFIG_FILE\" > /timeplus/sink.yaml;  /timeplus/cardemo --config /timeplus/.cardemo.yaml -f /timeplus/sink.yaml"
    environment:
      CONSOLE_CONFIG_FILE: |
        sinks:
          - type: proton
            properties:
              interval: 200
              host: proton
    depends_on:
      - proton
