version: '3'
services:
  proton:
    image: ghcr.io/timeplus-io/proton:latest
    container_name: proton
    pull_policy: always
    ports:
      - "3218:3218" # HTTP Streaming
      - "8123:8123" # HTTP Snapshot
      - "8463:8463" # TCP Streaming
      - "7587:7587" # TCP Snapshot
      - "9444:9444" # KV port
  grafana:
    image: grafana/grafana:latest
    pull_policy: always
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 1
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: timeplus-proton-datasource
      GF_INSTALL_PLUGINS: https://timeplus.io/timeplus-proton-datasource-1.0.3a.zip;timeplus-proton-datasource
    volumes:
      - ./provisioning:/etc/grafana/provisioning

  carsharing_datagen:
    image: timeplus/cardemo:latest
    entrypoint: /bin/sh
    command: -c "sleep 15 && echo \"$$CONSOLE_CONFIG_FILE\" > /timeplus/sink.yaml;  /timeplus/cardemo --config /timeplus/.cardemo.yaml -f /timeplus/sink.yaml"
    environment:
      CONSOLE_CONFIG_FILE: |
        sinks:
          - type: proton
            properties:
              interval: 200
              host: proton
    depends_on:
      - proton
